def sample_weather_data():
    return [
        {
            "monday": "frost, low of 50F, high of 60F",
            "tuesday": "rain, low of 20F, high of 30F",
            "friday": "hot, low of 70F, high of 80F",
            "wednesday": "snow, low of 80F, high of 100F",
            "thursday": "cloudy, low of 60F, high of 80F",
            "sunday": "cloudy, low of 50F, high of 70F",
            "location": "carson",
            "saturday": "snow, low of 20F, high of 30F",
            "today": "monday"
        },
        {
            "monday": "dry, low of 20F, high of 30F",
            "tuesday": "clear skies, low of 90F, high of 100F",
            "friday": "cloudy, low of 30F, high of 50F",
            "wednesday": "drizzle, low of 40F, high of 50F",
            "thursday": "overcast, low of 60F, high of 70F",
            "sunday": "dry, low of 70F, high of 90F",
            "location": "new york",
            "saturday": "dry, low of 40F, high of 50F",
            "today": "monday"
        },
        {
            "monday": "foggy, low of 70F, high of 90F",
            "tuesday": "hot, low of 70F, high of 90F",
            "friday": "blizzard, low of 20F, high of 40F",
            "wednesday": "snow, low of 90F, high of 100F",
            "thursday": "windy, low of 60F, high of 80F",
            "sunday": "raining, low of 90F, high of 100F",
            "location": "brentwood",
            "saturday": "raining, low of 60F, high of 80F",
            "today": "monday"
        },
        {
            "monday": "foggy, low of 20F, high of 40F",
            "tuesday": "stormy, low of 60F, high of 70F",
            "friday": "cloudy, low of 40F, high of 50F",
            "wednesday": "overcast, low of 60F, high of 80F",
            "thursday": "rain, low of 80F, high of 100F",
            "sunday": "warm, low of 70F, high of 80F",
            "location": "san mateo",
            "saturday": "dry, low of 70F, high of 80F",
            "today": "monday"
        },
        {
            "monday": "rain, low of 80F, high of 90F",
            "tuesday": "rain, low of 50F, high of 60F",
            "friday": "warm, low of 70F, high of 80F",
            "wednesday": "foggy, low of 20F, high of 40F",
            "thursday": "dry, low of 30F, high of 40F",
            "sunday": "snow, low of 30F, high of 40F",
            "location": "oakland",
            "saturday": "cloudy, low of 70F, high of 80F",
            "today": "monday"
        },
        {
            "monday": "windy, low of 70F, high of 80F",
            "tuesday": "cloudy, low of 60F, high of 70F",
            "friday": "rain, low of 70F, high of 90F",
            "wednesday": "rain, low of 30F, high of 50F",
            "thursday": "clear skies, low of 60F, high of 80F",
            "sunday": "overcast, low of 30F, high of 40F",
            "location": "cleveland",
            "saturday": "raining, low of 40F, high of 60F",
            "today": "monday"
        },
        {
            "monday": "cloudy, low of 70F, high of 90F",
            "tuesday": "foggy, low of 20F, high of 30F",
            "friday": "windy, low of 30F, high of 40F",
            "wednesday": "clear skies, low of 90F, high of 100F",
            "thursday": "clear skies, low of 40F, high of 60F",
            "sunday": "stormy, low of 60F, high of 80F",
            "location": "grand rapids",
            "saturday": "rain, low of 90F, high of 100F",
            "today": "monday"
        }
    ]


def sample_schedule_data():
    return [
               {
                   "room": "conference room 100",
                   "agenda": "discuss the company picnic",
                   "time": "7 pm",
                   "date": "thursday",
                   "party": "HR",
                   "event": "meeting"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "2 pm",
                   "date": "thursday",
                   "party": "-",
                   "event": "swimming activity"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "11 am",
                   "date": "monday",
                   "party": "-",
                   "event": "football activity"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "7 pm",
                   "date": "monday",
                   "party": "-",
                   "event": "yoga activity"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "7 pm",
                   "date": "friday",
                   "party": "-",
                   "event": "dentist"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "10 am",
                   "date": "wednesday",
                   "party": "-",
                   "event": "lab appointment"
               }
           ] + [
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "1 pm",
                   "date": "wednesday",
                   "party": "-",
                   "event": "lab appointment"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "7 pm",
                   "date": "monday",
                   "party": "-",
                   "event": "doctor appointment"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "11 am",
                   "date": "thursday",
                   "party": "-",
                   "event": "dentist"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "2 pm",
                   "date": "thursday",
                   "party": "-",
                   "event": "swimming activity"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "2 pm",
                   "date": "wednesday",
                   "party": "-",
                   "event": "yoga activity"
               },
               {
                   "room": "-",
                   "agenda": "-",
                   "time": "2 pm",
                   "date": "tuesday",
                   "party": "-",
                   "event": "dentist appointment"
               }
           ]


def sample_poi_data():
    return [
        {"address": "593 Arrowhead Way",
         "poi": "Chef Chu's",
         "type": "chinese restaurant"},
        {"address": "394 Van Ness Ave", "poi": "Coupa", "type": "coffee or tea place"},
        {"address": "408 University Ave",
         "poi": "Trader Joes",
         "type": "grocery store"},
        {"address": "113 Anton Ct", "poi": "Round Table", "type": "pizza restaurant"},
        {"address": "1313 Chester Ave",
         "poi": "Hacienda Market",
         "type": "grocery store"},
        {"address": "465 Arcadia Pl", "poi": "Four Seasons", "type": "rest stop"},
        {"address": "830 Almanor Ln", "poi": "tai pan", "type": "chinese restaurant"},
        {"address": "773 Alger Dr",
         "poi": "Stanford Shopping Center",
         "type": "shopping center"},
        {"address": "53 University Av", "poi": "Shell", "type": "gas station"},
        {"address": "657 Ames Ave", "poi": "The Clement Hotel", "type": "rest stop"},
        {"address": "792 Bedoin Street",
         "poi": "Starbucks",
         "type": "coffee or tea place"},
        {"address": "329 El Camino Real", "poi": "The Westin", "type": "rest stop"},
        {"address": "383 University Ave",
         "poi": "Town and Country",
         "type": "shopping center"},
        {"address": "452 Arcadia Pl", "poi": "Safeway", "type": "grocery store"},
        {"address": "171 Oak Rd", "poi": "Topanga Mall", "type": "shopping center"},
        {"address": "842 Arrowhead Way",
         "poi": "Panda Express",
         "type": "chinese restaurant"},
        {"address": "704 El Camino Real",
         "poi": "Pizza Hut",
         "type": "pizza restaurant"},
        {"address": "899 Ames Ct",
         "poi": "Stanford Childrens Health",
         "type": "hospital"},
        {"address": "5677 southwest 4th street",
         "poi": "5677 southwest 4th street",
         "type": "certain address"},
        {"address": "5672 barringer street",
         "poi": "5672 barringer street",
         "type": "certain address"},
        {"address": "214 El Camino Real",
         "poi": "Stanford Express Care",
         "type": "hospital"},
        {"address": "638 Amherst St",
         "poi": "Sigona Farmers Market",
         "type": "grocery store"},
        {"address": "611 Ames Ave",
         "poi": "Palo Alto Medical Foundation",
         "type": "hospital"},
        {"address": "434 Arastradero Rd",
         "poi": "Ravenswood Shopping Center",
         "type": "shopping center"},
        {"address": "338 Alester Ave",
         "poi": "Midtown Shopping Center",
         "type": "shopping center"},
        {"address": "271 Springer Street",
         "poi": "Mandarin Roots",
         "type": "chinese restaurant"},
        {"address": "753 University Ave", "poi": "Comfort Inn", "type": "rest stop"},
        {"address": "669 El Camino Real",
         "poi": "P.F. Changs",
         "type": "chinese restaurant"},
        {"address": "915 Arbol Dr", "poi": "Pizza Chicago", "type": "pizza restaurant"},
        {"address": "333 Arbol Dr", "poi": "Travelers Lodge", "type": "rest stop"},
        {"address": "436 Alger Dr",
         "poi": "Palo Alto Cafe",
         "type": "coffee or tea place"},
        {"address": "5677 springer street",
         "poi": "5677 springer street",
         "type": "certain address"},
        {"address": "113 Arbol Dr", "poi": "Jing Jing", "type": "chinese restaurant"},
        {"address": "409 Bollard St", "poi": "Willows Market", "type": "grocery store"},
        {"address": "776 Arastradero Rd", "poi": "Dominos", "type": "pizza restaurant"},
        {"address": "269 Alger Dr",
         "poi": "Cafe Venetia",
         "type": "coffee or tea place"},
        {"address": "110 Arastradero Rd",
         "poi": "Papa Johns",
         "type": "pizza restaurant"},
        {"address": "550 Alester Ave", "poi": "Dish Parking", "type": "parking garage"},
        {"address": "578 Arbol Dr", "poi": "Hotel Keen", "type": "rest stop"},
        {"address": "9981 Archuleta Ave",
         "poi": "Peets Coffee",
         "type": "coffee or tea place"},
        {"address": "200 Alester Ave", "poi": "Valero", "type": "gas station"},
        {"address": "819 Alma St", "poi": "Whole Foods", "type": "grocery store"},
        {"address": "91 El Camino Real", "poi": "76", "type": "gas station"},
        {"address": "583 Alester Ave", "poi": "Philz", "type": "coffee or tea place"},
        {"address": "270 Altaire Walk",
         "poi": "Civic Center Garage",
         "type": "parking garage"},
        {"address": "610 Amarillo Ave",
         "poi": "Stanford Oval Parking",
         "type": "parking garage"},
        {"address": "347 Alta Mesa Ave", "poi": "jills house", "type": "friends house"},
        {"address": "880 Ames Ct", "poi": "Webster Garage", "type": "parking garage"},
        {"address": "864 Almanor Ln", "poi": "jacks house", "type": "friends house"},
        {"address": "56 cadwell street",
         "poi": "home_2",
         "type": "home"},
        {"address": "5671 barringer street",
         "poi": "home_3",
         "type": "home"},
        {"address": "528 Anton Ct",
         "poi": "Pizza My Heart",
         "type": "pizza restaurant"},
        {"address": "10 ames street",
         "poi": "home_1",
         "type": "home"},
        {"address": "580 Van Ness Ave", "poi": "toms house", "type": "friends house"},
        {"address": "481 Amaranta Ave",
         "poi": "Palo Alto Garage R",
         "type": "parking garage"},
        {"address": "783 Arcadia Pl", "poi": "Chevron", "type": "gas station"},
        {"address": "145 Amherst St", "poi": "Teavana", "type": "coffee or tea place"}
    ]